VIDEO AULA/Cleyton Ferrari/VS_EntityFramework_-_MigrationNaPratica/CadastroDeProdutos/CadastroDeProdutos/Controllers/AuthController.cs
using CadastroDeProdutos.DAL;
using CadastroDeProdutos.Models;
using CadastroDeProdutos.ModelsViews;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DemoAuthentication.Controllers
{
    public class AuthController : Controller
    {
        ProdutoContexto db = new ProdutoContexto();

        // ============================= CREATE ==================================
        public ActionResult Create()
        {
            return View(new Utilisateur());
        }
        [HttpPost]
        public ActionResult Create(Utilisateur user)
        {
            if (ModelState.IsValid)
            {
                string password = user.PasswordRepeated;
                byte[] encodedPassword = new UTF8Encoding().GetBytes(password);
                byte[] hash = ((HashAlgorithm)CryptoConfig.CreateFromName("MD5")).ComputeHash(encodedPassword);
                string encoded = BitConverter.ToString(hash);
                user.PasswordRepeated = encoded;

                db.Utilisateurs.Add(user);
                db.SaveChanges();
                FormsAuthentication.SetAuthCookie(user.UtilisateurID.ToString(), false);
                return RedirectToAction("Index", "Home");
            }
            //return utilisateur.Id;
            return View(user);
        }

        //public string HashMotDePasse()
        //{
            
        //    get { return _hashMotDePasse; }
        //    set{
        //        _hashMotDePasse = PasswordHash.PasswordHash.CreateHash(value);
        //    }
        //}

// ============================= Login ==================================
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel userModel, string ReturnUrl)
        {
            if (IsValid(userModel))
            {
                FormsAuthentication.SetAuthCookie(userModel.NomUtilisateur, userModel.Persistant);
                if (!string.IsNullOrWhiteSpace(ReturnUrl) && Url.IsLocalUrl(ReturnUrl))
                    return Redirect(ReturnUrl);
                return Redirect("/");
            }
            else
            {
                ModelState.AddModelError("", "Le nom d'utilisateur ou le mot de passe est incorrect. ");
                return View(userModel);
            }

        }

        private bool IsValid(LoginModel user)
        {
            Utilisateur userFromBd = db.Utilisateurs.FirstOrDefault(u => u.NomUtilisateur == user.NomUtilisateur && u.Password == user.Password);
            if (userFromBd != null)
                return (true);
            return (false);
        }

        // ============================= Logout ==================================
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }

    }
}

VIDEO AULA/Cleyton Ferrari/VS_EntityFramework_-_MigrationNaPratica/CadastroDeProdutos/CadastroDeProdutos/Controllers/ProdutoController.cs
using CadastroDeProdutos.DAL;
using CadastroDeProdutos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CadastroDeProdutos.Controllers
{
    public class ProdutoController : Controller
    {

        ProdutoContexto db = new ProdutoContexto();

        // ============================= LIST ==================================
        public ActionResult Index()
        {
            return View(db.Produtos.ToList());
        }

        // ============================= DETAILS ==================================
        public ActionResult Details(int id)
        {
            Produto produto = db.Produtos.Find(id);
            return View(produto);
        }

        // ============================= CREATE ==================================
        [Authorize]
        public ActionResult Create()
        {
            return View(new Produto());
        }

        [HttpPost]
        public ActionResult Create(Produto p)
        {
            if (ModelState.IsValid)
            {
                db.Produtos.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(p);
        }

        // ============================= EDIT ==================================
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Edit(Produto produto)
        {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    db.Entry(produto).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
        }

        // ============================= DELITE ==================================
        [Authorize(Roles = "Administrateur")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto p = db.Produtos.Find(id);
            if (p == null)
            {
                return HttpNotFound();
            }
            return View(p);//Demande la confirmation avant le delete
        }

        // POST: Produto/DeletePost/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            try
            {
                Produto produtoToDelite = db.Produtos.Where(x => x.ProdutoID == id).First();
                db.Set<Produto>().Remove(produtoToDelite);//delete la video de la table
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

VIDEO AULA/Cleyton Ferrari/VS_EntityFramework_-_MigrationNaPratica/CadastroDeProdutos/CadastroDeProdutos/Controllers/UtilisateurController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CadastroDeProdutos.DAL;
using CadastroDeProdutos.Models;
using System.Web.Security;

namespace CadastroDeProdutos.Controllers
{

    public class UtilisateurController : Controller
    {
        private ProdutoContexto db = new ProdutoContexto();

        // ============================= Index ==================================
        public ActionResult Index()
        {
            return View(db.Utilisateurs.ToList());
        }


        // ============================= Details ==================================
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        // ============================= Edit ==================================

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UtilisateurID,NomUtilisateur,Password,TypeUtilisateur")] Utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utilisateur).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(utilisateur);
        }
        // ============================= Delete ==================================
        [Authorize(Roles = "Membre")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            db.Utilisateurs.Remove(utilisateur);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // ============================= Dispose ==================================

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VIDEO AULA/Cleyton Ferrari/VS_EntityFramework_-_MigrationNaPratica/CadastroDeProdutos/CadastroDeProdutos/Views/Shared/_DropdownMenuLogin.cshtml
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Connection<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
        <!--Si l'utilisateur n'est pas connecté-->
        @if (!User.Identity.IsAuthenticated)
        {
            <li>@Html.ActionLink("Login", "Login", "Auth")</li>
            <li>@Html.ActionLink("Logout", "Logout", "Auth")</li>
            <li>@Html.ActionLink("Create", "Create", "Auth")</li>
            
        }

        <!--Si l'utilisateur est connecté-->
        <!--Afficher Compte, Pokémons Favoris, Logout-->
        @if (User.Identity.IsAuthenticated)
        {
            <li>@Html.ActionLink("Lista de produtos", "Index", "Home")</li>
            <li>@Html.ActionLink("Lista de usuarios", "Index", "Utilisateur")</li>
            //les playlist,videos,
        }
    </ul>
</li>

VIDEO AULA/Cleyton Ferrari/VS_EntityFramework_-_MigrationNaPratica/CadastroDeProdutos/CadastroDeProdutos/Views/Shared/_Footer.cshtml
<hr />
<footer>
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
</footer>

VIDEO AULA/Cleyton Ferrari/VS_EntityFramework_-_MigrationNaPratica/CadastroDeProdutos/CadastroDeProdutos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    @Html.Partial("_Menu")
    <div class="container body-content">
        @RenderBody()
        @Html.Partial("_Footer")
    </div>
</body>
</html>

VIDEO AULA/Cleyton Ferrari/VS_EntityFramework_-_MigrationNaPratica/CadastroDeProdutos/CadastroDeProdutos/Views/Shared/_Menu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Utilisateurs", "Index", "Home")</li>
                <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                <li>@Html.Partial("_DropdownMenuLogin")</li>
                @*<li>@Html.ActionLink("Login", "Login", "Auth")</li>*@
                @*<li>@Html.ActionLink("Create Compte", "Create", "Auth")</li>*@
            </ul>
        </div>
    </div>
</div>